services:
  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: server/Dockerfile
    image: cs467registry.azurecr.io/jobtrekker-app-api
  client:
    platform: linux/amd64
    build:
      context: .
      dockerfile: client/Dockerfile
    image: cs467registry.azurecr.io/jobtrekker-app-client
    ports:
      - "3000:80"