services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    image: test/jobtrekker-app-api
    environment:
      - FLASK_ENV=test
      - FLASK_DEBUG=1
    depends_on:
      - api-mongodb
  api-mongodb:
    image: mongo:6-jammy
    ports:
      - 27017:27017
    container_name: mongodb-test

